// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlplxfxyezjikmtjtuxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscGx4Znh5ZXpqaWttdGp0dXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTg3ODEsImV4cCI6MjA2OTI5NDc4MX0.pVyxpv8W9EdlDNbuaskgH5CW1MV-tcMrIoWQVNAyngU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});